id: ENVIRONMENT_LAND_CONTINENTAL_SUBARCTIC
type: BIOME
abstract: true

colors:
  fog: 0xc0d8ff
  water: 0x205E83
  water-fog: 0x205E83
  sky: 0x839eff
  grass: 0x80B497
  foliage: 0x60A17B

  climate:
    precipitation: snow
    temperature: 0.0
    downfall: 0.4