id: ENVIRONMENT_LAND_CONTINENTAL_HUMID
type: BIOME
abstract: true

colors:
  fog: 0xc0d8ff
  water: 0x287082
  water-fog: 0x287082
  sky: 0x78a3ff
  grass: 0x83BB6D
  foliage: 0x63A948

  climate:
    precipitation: rain
    temperature: 0.8
    downfall: 0.4