id: ENVIRONMENT_LAND_TEMPERATE_SUBTROPICAL_HUMID
type: BIOME
abstract: true

colors:
  fog: 0xc0d8ff
  water: 0x20A3CC
  water-fog: 0x20A3CC
  sky: 0x78a7ff
  grass: 0x71cf48
  foliage: 0x8bde5b

  climate:
    precipitation: rain
    temperature: 0.75
    downfall: 0.8