id: ENVIRONMENT_LAND_POLAR_ICE_CAP
type: BIOME
abstract: true

colors:
  fog: 0xc0d8ff
  water: 0x14559B
  water-fog: 0x14559B
  sky: 0x7fa1ff
  grass: 0x80B497
  foliage: 0x60A17B

  climate:
    precipitation: snow
    temperature: -0.5
    temperature-modifier: FROZEN
    downfall: 0.1