id: ENVIRONMENT_LAND_TROPICAL_SAVANNA
type: BIOME
abstract: true

colors:
  fog: 0xc0d8ff
  water: 0x2C8B9C
  water-fog: 0x2C8B9C
  sky: 0x6eb1ff
  grass: 0xBFB755
  foliage: 0xAEA42A


  climate:
    precipitation: rain
    temperature: 1.2
    downfall: 0.0