id: ENVIRONMENT_LAND_DRY_WARM_SEMI_ARID
type: BIOME
abstract: true

colors:
  fog: 0xfffce1
  water: 0x1A7AA1
  water-fog: 0x1A7AA1
  sky: 0xc5ffff
  grass: 0xbdd394
  foliage: 0x8cbb5e

  climate:
    temperature: 1.5
    downfall: 0.1